### ISSUE TITLE
Take into account sale taxes

### ISSUE THREAD

**Issue by louim** [ammobinDOTca/ammobin-client#69]
It would be great if the site could take into account sale taxes. 

How I see it could work:

- Users are located with their IP, or just select a dropdown with their province.
- User could opt out of the feature (with a checkbox or the like)
- Sale taxes would be calculated based on the province the user is and the province the vendor is.

For example, as a Quebec resident, if I choose a Quebec retailer (like Canadian Tire or Sail), it would add Quebec GST 5% and QST (Quebec Sales Tax) 9.975% to the prices. If I choose a retailer from Ontario, it would add only the 5% GST to the prices.

What do you think?

**Comment by nexus-uw** [comment]
hi @louim ,

while I agreed with the general idea of displaying prices AFTER tax, I dont see the value in being an earlier adopter of it, especially when ammobin.ca is linking to other sites (which display before tax). 
The majority of issues brought to my attention have been related to the accuracy of the data being displayed, and deliberately changing the display price could add to it.

Additionally, sales tax is constant addition across to consumer regardless of where they are shopping, so it does no differential a Ontario retailer from a Quebec one. I see  #49 bringing more value to to user since it could say if it makes sense to place an order to a farther away retailer rather than just go to the local store and pay a little more (and save on shipping).

This all being said, if you are able to find a clean + clear way of inserting it into the site, feel free to submit a PR.

Simon

ps. ill leave this issue open for a while
